CREATE DATABASE IF NOT EXISTS service_map CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE service_map;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    fullname VARCHAR(100) NOT NULL,
    session_token VARCHAR(64) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cable_points (
    id VARCHAR(50) PRIMARY KEY,
    date DATE DEFAULT NULL,
    category VARCHAR(100) DEFAULT NULL,
    line_unit VARCHAR(200) DEFAULT NULL,
    tambon VARCHAR(100) DEFAULT NULL,
    work_area VARCHAR(100) DEFAULT NULL,
    village VARCHAR(200) DEFAULT NULL,
    note TEXT DEFAULT NULL,
    status VARCHAR(50) DEFAULT 'รอดำเนินการ',
    run_advice VARCHAR(200) DEFAULT NULL,
    coords VARCHAR(100) DEFAULT NULL,
    lat DECIMAL(10,7) DEFAULT NULL,
    lng DECIMAL(10,7) DEFAULT NULL,
    images JSON DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
